[main]
input = './examples/input'
output = './examples/output'
filename_mask = ['trade']

[performance]
parallel = true
num_threads = 8

[metrics]
enabled = false
types = ['median', 'mean', 'p95', 'p99']

[streaming]
enabled = false
buffer_size = 2097152